 version: "3" 
 
 services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
      
  blog:
    image: dblog:latest
    links:
       - redis:redis
    depends_on:
       - redis
    ports:
      - 8000:8000
    volumes:
      - /opt/django_blog/django_root:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
