# Generated by Django 4.1 on 2022-08-20 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('item_image', models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='uploads/articles/%Y/%m/%d/')),
                ('article_content', models.TextField(blank=True, null=True)),
                ('sub_reqd', models.BooleanField(default=False)),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='uploads/articles/%Y/%m/%d/')),
                ('sub_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_image', models.ImageField(null=True, upload_to='uploads/categories/%Y/%m/%d/')),
                ('cat_summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='my_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('item_image', models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('videoURL', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category')),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('tutorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='my_app.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialFieldContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='my_app.tutorialfield')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialFieldContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/')),
                ('field_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.tutorialfieldcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('item_image', models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category')),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=240, null=True)),
                ('author', models.CharField(blank=True, max_length=240, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.article')),
                ('tutorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.tutorial')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
        ),
    ]
