# Generated by Django 4.1 on 2022-08-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
