# Generated by Django 4.1 on 2022-08-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_category_show_in_posts_category_show_in_services_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='references',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='sub_title',
        ),
    ]
