# Generated by Django 4.0.5 on 2022-06-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='approved',
            new_name='isProject',
        ),
    ]
