# Generated by Django 4.1 on 2022-08-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_service_options_alter_tutorial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='videoURL',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tutorials/videos/%Y/%m/%d/'),
        ),
    ]
