# Generated by Django 4.1 on 2022-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_personaldata_alter_article_sub_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
