# Generated by Django 4.1 on 2022-08-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='field1_content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='introduction',
            new_name='field2_content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='s_media0',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='s_media1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='s_media2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='s_media3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='s_media4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='s_media5',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f1_m0',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f1_m1',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f1_m2',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f1_m3',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f1_m4',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f1_m5',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f2_m0',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f2_m1',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f2_m2',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f2_m3',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f2_m4',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f2_m5',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f3_m0',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f3_m1',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f3_m2',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f3_m3',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f3_m4',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f3_m5',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f4_m0',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f4_m1',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f4_m2',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f4_m3',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f4_m4',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f4_m5',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f5_m0',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f5_m1',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f5_m2',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f5_m3',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f5_m4',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='f5_m5',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field1_title',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field2_title',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field3_content',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field3_title',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field4_content',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field4_title',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field5_content',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='field5_title',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
