# Generated by Django 4.1 on 2022-08-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_personaldata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/personaldata/resumes/%Y/%m/%d/'),
        ),
    ]
