# Generated by Django 4.1 on 2022-08-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_rename_description_blogpost_field1_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
