# Generated by Django 4.1 on 2022-08-19 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_item_remove_comment_blogpost_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.BooleanField(default=False)),
                ('videoURL', models.URLField(default='NULL')),
                ('field1_reqd', models.BooleanField(default=False)),
                ('field1_title', models.CharField(default='NULL', max_length=100)),
                ('field1_content', models.TextField(default='NULL')),
                ('f1_m0', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f1_m1', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f1_m2', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f1_m3', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f1_m4', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f1_m5', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('field2_reqd', models.BooleanField(default=False)),
                ('field2_title', models.CharField(default='NULL', max_length=100)),
                ('field2_content', models.TextField(default='NULL')),
                ('f2_m0', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f2_m1', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f2_m2', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f2_m3', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f2_m4', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f2_m5', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('field3_reqd', models.BooleanField(default=False)),
                ('field3_title', models.CharField(default='NULL', max_length=100)),
                ('field3_content', models.TextField(default='NULL')),
                ('f3_m0', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f3_m1', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f3_m2', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f3_m3', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f3_m4', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f3_m5', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('field4_reqd', models.BooleanField(default=False)),
                ('field4_title', models.CharField(default='NULL', max_length=100)),
                ('field4_content', models.TextField(default='NULL')),
                ('f4_m0', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f4_m1', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f4_m2', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f4_m3', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f4_m4', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f4_m5', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('field5_reqd', models.BooleanField(default=False)),
                ('field5_title', models.CharField(default='NULL', max_length=100)),
                ('field5_content', models.TextField(default='NULL')),
                ('f5_m0', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f5_m1', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f5_m2', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f5_m3', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f5_m4', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f5_m5', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('field6_reqd', models.BooleanField(default=False)),
                ('field6_title', models.CharField(default='NULL', max_length=100)),
                ('field6_content', models.TextField(default='NULL')),
                ('f6_m0', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f6_m1', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f6_m2', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f6_m3', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f6_m4', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('f6_m5', models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
