# Generated by Django 4.1 on 2022-08-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_tutorial_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='video',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='item',
            name='typeslug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/')),
                ('article_content', models.TextField(default='NULL')),
                ('sub_reqd', models.BooleanField(default=False)),
                ('sub_image', models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/')),
                ('sub_content', models.TextField(default='NULL')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.post')),
            ],
        ),
    ]
