# Generated by Django 4.1 on 2022-08-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_remove_tutorial_video_item_item_image_item_typeslug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f1_m0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f1_m1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f1_m2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f1_m3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f1_m4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f1_m5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f2_m0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f2_m1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f2_m2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f2_m3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f2_m4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f2_m5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f3_m0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f3_m1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f3_m2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f3_m3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f3_m4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f3_m5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f4_m0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f4_m1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f4_m2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f4_m3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f4_m4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f4_m5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f5_m0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f5_m1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f5_m2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f5_m3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f5_m4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f5_m5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f6_m0',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f6_m1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f6_m2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f6_m3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f6_m4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='f6_m5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorials/%Y/%m/%d/'),
        ),
    ]
