# Generated by Django 4.1 on 2022-08-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_article_main_image_alter_article_sub_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='service',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='post',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='item_image',
            field=models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='typeslug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.tutorial'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='item_image',
            field=models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='service',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='typeslug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='item_image',
            field=models.ImageField(null=True, upload_to='uploads/items/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='typeslug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
