# Generated by Django 4.1 on 2022-08-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_comment_author_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='field1_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='field2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='field3_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='field4_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='field5_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='field6_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
