# Generated by Django 4.1 on 2022-08-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_alter_article_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='typeslug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='typeslug',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='typeslug',
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
