# Generated by Django 4.1 on 2022-08-20 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_tutorialfieldmedia_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialfield',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.tutorial'),
        ),
    ]
