# Generated by Django 4.1 on 2022-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_tutorialfield_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
