# Generated by Django 4.1 on 2022-08-20 03:56

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_service_sub_title_tutorial_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='videoURL',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
